#[derive(Hash, Eq, PartialEq, Debug, Clone, Copy)]
pub enum Operation {
    Touch,
    Input,
    CurrentResult,
    Addition,
    Subtraction,
    Multiplication,
    Modulo,
    Division,
    Exponential,
    Negation,
    ExclusiveRange,
    InclusiveRange,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    Equality,
    Inequality,
    LogicalAnd,
    LogicalOr,
    LogicalNot,
    Group,
    None,
}
