[package]
name = "sel_common"
version = "0.1.0"
authors = ["chadcollins <chadrcollins91@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
serde = "1.0.90"
serde_derive = "1.0.90"
bincode = "1.1.3"
