[package]
name = "sel_compiler"
version = "0.1.0"
authors = ["chadcollins <chadrcollins91@gmail.com>"]
edition = "2018"

[dependencies]
sel_common = { path = "../sel_common" }
byteorder = "1.3.1"
unicode-segmentation = "1.2.1"
