[package]
name = "sel_executor"
version = "0.1.0"
authors = ["chadcollins <chadrcollins91@gmail.com>"]
edition = "2018"

[dependencies]
sel_common = { path = "../sel_common" }
byteorder = "1.3.1"

[dev-dependencies]
sel_compiler = { path = "../sel_compiler" }
